export const menu: {
    pizza: Record<string, [string, number, string, string?]>,
    burger: Record<string, [string, number, string, string?]>,
    smashburger: Record<string, [string, number, string, string?]>,
    extras: Record<string, [string, number, string]>,
    drinks: Record<string, [string, number, string]>,
    sos: {name: string, price: number}[]
    pizzaExtras: {name: string, price: number}[]
    burgerOptions: {name: string, price: number}[]
} = {
    pizza: {
        "Margarita": ["Sos pomidorowy, mozzarella, świeża bazylia", 29, "/images/marg.svg", "vege",],
        "Capricciosa": ["Sos pomidorowy, mozzarella, szynka, pieczarki", 34, "/images/capr.svg", ""],
        "Primavera": ["Sos pomidorowy, mozzarella, salami, pieczarki", 34, "/images/margarita.svg", ""],
        "Salami": ["Sos pomidorowy, mozzarella, salami, czosnek", 34, "/images/margarita.svg", ""],
        "Diabola": ["Sos pomidorowy, mozzarella, spianata, jalapeño, płatki chili", 36, "/images/margarita.svg", "ostra"],
        "Vegetariana": ["Sos pomidorowy, mozzarella, ser feta, cukinia, rukola, suszone pomidory", 36, "/images/vegetariana.svg", "vege"],
        "Hawajska": ["Sos pomidorowy, mozzarella, kurczak, ananas, kukurydza", 38, "/images/hawajska.svg", ""],
        "Cezar": ["Sos biały, sałata, kurczak, parmezan, czerwona cebula, czarne oliwki", 38, "/images/margarita.svg", ""],
        "Pizza z gruszką": ["Sos pomidorowy, mozzarella, gruszka, ser feta, nasiona, rukola/szpinak", 38, "/images/z-gruszka.svg", "vege"],
        "Pollo BBQ": ["Sos BBQ, mozzarella, grillowany kurczak, kukurydza, szczypiorek, prażona cebula", 38, "/images/margarita.svg", ""],
        "Myśliwska": ["Sos pomidorowy, mozzarella, frankfurterki, czarne oliwki, płatki chili, sos BBQ", 39, "/images/mysliwska.svg", "ostra"],
        "Carne": ["Sos pomidorowy, mozzarella, boczek, spianata, czerwona cebula, papryczki jalapeño", 40, "/images/4-miesa.svg", "ostra"],
        "4 Sery": ["Sos biały, mozzarella, feta, gorgonzola, Grana Padano", 39, "/images/4-sery.png", "vege"],
        "Salama Bianca": ["Sos biały, mozzarella, pieczarki, spianata, czosnek, gorgonzola", 43, "/images/bianca.svg", ""],
        "Parma": ["Sos BBQ, mozzarella, prosciutto, kukurydza, szczypiorek, prażona cebula", 43, "/images/parma.png", ""],
        "Quattro Carni": ["Sos pomidorowy, salami, szynka, spianata, frankfurterki, szczypiorek", 43, "/images/4-miesa.svg", ""],
    },
    burger: {
        "Klasyczny": ["Bułka, wołowina 200 g, sałata, pomidor, sos autorski", 27, "/images/ser-bekon2.png", ""],
        "Z cheddarem": ["Bułka, wołowina 200 g, cheddar, sałata, pomidor, sos autorski", 34, "/images/ser-bekon2.png", ""],
        "Veganski": ["Bułka, mozzarella smażona w panierce, pomidory suszone, cebula prażona, sałata, wegańskie mayo", 36, "/images/veganski.png", "vege"],
        "Ser Bekon": ["Bułka, wołowina 200 g, cheddar, boczek, sałata, pomidor, sos autorski", 37, "/images/ser-bekon2.png", ""],
        "Kurczak": ["Bułka, grillowany kurczak, sałata, pomidor, czerwona cebula, sos czosnkowy", 37,"/images/ser-bekon2.png", ""],
        "BBQ": ["Bułka, wołowina 200 g, cheddar, bekon, sałata, prażona cebula, sos BBQ", 37, "/images/bekon.svg", ""],
        "Ostry": ["Bułka, wołowina 200 g, sałata, papryczki jalapeño, sos sriracha, sos spicy", 39, "/images/ser-bekon2.png", "ostry"],
        "Drwalski": ["Bułka, wołowina 200 g, panierowany ser, bekon, prażona cebula, sos drwalski", 43, "/images/drwala.svg", ""],
        "Gigant": ["Bułka, podwójna wołowina, podwójny cheddar, bekon, sałata, pomidor, sos autorski", 52, "/images/ser-bekon2.png", ""]
    },
    smashburger: {
        "Smash Klasyczny": ["Maślana bułka, wołowina 100g, ogórek kiszony, czerwona cebula, sos firmowy", 20, "/images/serowy-smash.svg", ""],
        "Smash Serowy": ["Maślana bułka, wołowina 100g, podwójny cheddar, ogórek kiszony, czerwona cebula, sos firmowy", 24, "/images/serowy-smash.svg", ""],
        "Smash Ostry": ["Maślana bułka, wołowina 100g, cheddar, papryczki jalapeño, sos firmowy", 25, "/images/serowy-smash.svg", "ostry"],
        "Smash Bekon": ["Maślana bułka, wołowina 100g, bekon, cheddar, prażona cebula, sos firmowy", 29, "/images/serowy-smash.svg", ""],
        "Smash Egg&Bekon": ["Maślana bułka, wołowina 100 g, bekon, cheddar, jajko sadzone, czerwona cebula, sos firmowy", 31,"/images/egg-bekon.svg", ""],
    },
    extras: {
        "Frytki cienkie": ["Frytki cienkie z ketchupem", 14, "/images/krazki.png"],
        "Frytki stekowe": ["Frytki stekowe z ketchupem", 15, "/images/krazki.png"],
        "Frytki z batatów": ["Frytki z batatów z sosem do wyboru", 19, "/images/krazki.png"],
        "Frytki Special": ["Z parmezanem i szczypiorkiem, sos do wyboru", 19, "/images/krazki.png"],
        "Krążki cebulowe ": ["Krążki cebulowe (8 szt.) z sosem do wyboru", 19, "/images/krazki.png"],
        "Mozzarella sticks": ["Mozzarella sticks (5 szt.) z sosem do wyboru", 19, "/images/krazki.png"],

    },
    drinks: {
        "Coca-cola": ["", 9, "/images/margarita.svg"],
        "Fanta": ["", 9, "/images/margarita.svg"],
        "Sprite": ["", 9, "/images/margarita.svg"],
        "Woda niegazowana": ["", 9, "/images/margarita.svg"],
        "Woda gazowana": ["", 9, "/images/margarita.svg"],
        "On Lemon": ["", 9, "/images/margarita.svg"],
        "On Lemon z Gruszka": ["", 9, "/images/margarita.svg"],
        "On Lemon z Ananasem": ["", 9, "/images/margarita.svg"],
    },
    sos: [
        { name: "Śmietanowy", price: 4 },
        { name: "Czosnkowy", price: 4 },
        { name: "BBQ", price: 4 },
        { name: "Żurawlina", price: 4 },
        { name: "Drwalski", price: 4 },
        { name: "Serowy", price: 4 },
        { name: "Ketchup", price: 4 },
        { name: "Mayonez", price: 4 },
        { name: "Miodowo-musztardowy", price: 4 },
        {name: "Spicy mayo", price: 5},
        {name: "Pesto mayo", price: 5},
        {name: "Oliwa z oliwek", price: 5},
        {name: "Oliwa czosnkowa", price: 5},
    ],
    pizzaExtras: [
        { name: "Ananas", price: 4 },
        { name: "Czarne oliwki", price: 4 },
        { name: "Czerwona cebula", price: 4 },
        { name: "Czosnek", price: 4 },
        { name: "Jalapeńo", price: 4 },
        { name: "Kukurydza", price: 4 },
        { name: "Orzechi włoskie", price: 4 },
        { name: "Platki chilli", price: 4 },
        { name: "Pomidorki koktajlowe", price: 4 },
        { name: "Prazona cebula", price: 4 },
        { name: "Rukola", price: 4 },
        { name: "Suszone pomidory", price: 4 },
        { name: "Szczypiorek", price: 4 },
        { name: "Grana Padano", price: 5 },
        { name: "Gorgonzola", price: 5 },
        { name: "Pieczarki", price: 5 },
        { name: "Ser feta", price: 5 },
        { name: "Boczek", price: 6 },
        { name: "Frankfruterki", price: 6 },
        { name: "Kurczak", price: 6 },
        { name: "Prosciutto", price: 6 },
        { name: "Salami", price: 6 },
        { name: "Spianata", price: 6 },
        { name: "Szynka", price: 6 },

    ],
    burgerOptions: []
}
